name: Build & Test with Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c debug /p:TreatWarningsAsErrors=true

      - name: Test
        run: |
          dotnet test -c debug -v n \
            --collect:"XPlat Code Coverage" \
            --results-directory:artifacts/tests \
            /p:CollectCoverage=true \
            /p:CovAnalysisMode=Report \
            /p:CoverletOutputFormat=xml \
            /p:CoverletOutputDirectory="artifacts/tests"

      - name: Publish Zarn
        run: dotnet publish -c release --project Zarn/Zarn.csproj --no-restore

      - name: Publish Zarn.AspNetCore
        run: dotnet publish -c release --project Zarn.AspNetCore/Zarn.AspNetCore.csproj --no-restore

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v7
        with:
            path: artifacts/tests
